# Compile, orange. Compile writes the source tree's documents back as bytes. It is the
# inverse of decompile plugin (decompile-a-plugin).
...@../styles
shape: sequence_diagram
plugins: @../target-architecture.modbench_driving.plugins
plugins.label: Plugins
client: @../target-architecture.modbench_core.client
client.label: mEdit client
http: @../target-architecture.medit_driving.http
http.label: HTTP endpoints
commands: @../target-architecture.medit_core.commands
commands.label: Commands
source: @../target-architecture.medit_data.source
sourcerepo: @../target-architecture.medit_driven.sourcerepo
sourcerepo.label: Source repository
pluginadapter: @../target-architecture.medit_driven.pluginadapter
pluginadapter.label: Plugin adapter
plugin: @../target-architecture.medit_data.plugin
watcher: @../target-architecture.medit_driving.watcher
watcher.label: Mod watcher
projector: @../target-architecture.medit_driven.index.projector
projector.label: Projector

plugins -> client: compile {class: edit}
client -> http: envelope {class: edit}
http -> commands: envelope {class: edit}
source -> sourcerepo: documents {class: compile}
sourcerepo -> commands: documents {class: compile}
commands -> pluginadapter: bytes {class: compile}
pluginadapter -> plugin: bytes {class: compile}
plugin -> watcher: bytes {class: signal}
watcher -> projector: "plugin changed: validate by hash" {class: signal}
