import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { parsePlugins, setPluginEnabledInText, movePluginsInText } from './pluginsText';
import type { PluginEntry } from '../model';

const fixtureDir = join(__dirname, '..', 'test', 'fixtures', 'mo2-instance');
const defaultPlugins = () =>
  readFileSync(join(fixtureDir, 'profiles', 'Default', 'plugins.txt'), 'utf8');

const names = (text: string) => parsePlugins(text).map((e) => e.name);

describe('parsePlugins', () => {
  it('surfaces enabled/disabled entries in order, ignoring comment/blank lines', () => {
    const entries = parsePlugins('# header\r\n*Foo.esp\r\nBar.esp\r\n\r\n*Baz.esl\r\n');
    expect(entries).toEqual([
      { name: 'Foo.esp', enabled: true },
      { name: 'Bar.esp', enabled: false },
      { name: 'Baz.esl', enabled: true },
    ] satisfies PluginEntry[]);
  });

  it('strips a leading UTF-8 BOM so the top plugin is not silently dropped', () => {
    expect(parsePlugins('\uFEFF*First.esp\r\nSecond.esp\r\n')).toEqual([
      { name: 'First.esp', enabled: true },
      { name: 'Second.esp', enabled: false },
    ] satisfies PluginEntry[]);
  });

  it('parses the committed fixture (comment header + two enabled entries)', () => {
    expect(parsePlugins(defaultPlugins())).toEqual([
      { name: 'Unofficial Fallout 4 Patch.esp', enabled: true },
      { name: 'ccSBJFO4003-Grenade.esl', enabled: true },
    ] satisfies PluginEntry[]);
  });
});

describe('setPluginEnabledInText — byte-faithful surgical edit', () => {
  it('removes exactly one * and leaves every other byte (CRLF, comment) identical', () => {
    const input = defaultPlugins();
    const out = setPluginEnabledInText(input, 'Unofficial Fallout 4 Patch.esp', false);
    expect(out).toBe(input.replace('*Unofficial Fallout 4 Patch.esp', 'Unofficial Fallout 4 Patch.esp'));
    expect(out.length).toBe(input.length - 1);
    expect(out).toContain('# This file was automatically generated by Mod Organizer.\r\n');
    expect(out).toContain('*ccSBJFO4003-Grenade.esl\r\n');
  });

  it('is a no-op when the plugin already has the requested state', () => {
    const input = defaultPlugins();
    expect(setPluginEnabledInText(input, 'ccSBJFO4003-Grenade.esl', true)).toBe(input);
  });

  it('adds a * when enabling a disabled plugin, preserving comment/blank lines', () => {
    const input = '# header\r\nFoo.esp\r\n\r\nBar.esp\r\n';
    const out = setPluginEnabledInText(input, 'Foo.esp', true);
    expect(out).toBe('# header\r\n*Foo.esp\r\n\r\nBar.esp\r\n');
    expect(out.length).toBe(input.length + 1);
  });

  it('throws when the plugin name is not present', () => {
    expect(() => setPluginEnabledInText(defaultPlugins(), 'No Such.esp', false)).toThrow(/No Such\.esp/);
  });

  it('preserves a leading BOM when toggling the first line', () => {
    const out = setPluginEnabledInText('\uFEFF*First.esp\r\n*Second.esp\r\n', 'First.esp', false);
    expect(out).toBe('\uFEFFFirst.esp\r\n*Second.esp\r\n');
  });

  it('round-trips: disable then re-enable yields the original bytes', () => {
    const input = defaultPlugins();
    const disabled = setPluginEnabledInText(input, 'Unofficial Fallout 4 Patch.esp', false);
    expect(setPluginEnabledInText(disabled, 'Unofficial Fallout 4 Patch.esp', true)).toBe(input);
  });
});

describe('movePluginsInText — byte-faithful reorder', () => {
  const sample = '# header\r\n*A.esp\r\nB.esp\r\n*C.esp\r\nD.esp\r\n';

  it('moves a single plugin to the top (index 0), keeping the comment header first', () => {
    const out = movePluginsInText(sample, ['C.esp'], 0);
    expect(names(out)).toEqual(['C.esp', 'A.esp', 'B.esp', 'D.esp']);
    expect(out.startsWith('# header\r\n')).toBe(true);
    expect(out.length).toBe(sample.length);
  });

  it('moves a contiguous multi-selection as a block, preserving relative order', () => {
    const out = movePluginsInText(sample, ['B.esp', 'C.esp'], 3);
    // remove B,C → [A, D]; index 3 clamps to end → A, D, B, C
    expect(names(out)).toEqual(['A.esp', 'D.esp', 'B.esp', 'C.esp']);
  });

  it('moves a non-contiguous selection, ordering by source position not argument order', () => {
    // pass D before A; A precedes D in the file, so the moved block is A, D
    const out = movePluginsInText(sample, ['D.esp', 'A.esp'], 1);
    // remaining after removal: [B, C]; insert block before entry-index 1 (before C)
    expect(names(out)).toEqual(['B.esp', 'A.esp', 'D.esp', 'C.esp']);
  });

  it('clamps an out-of-range index to the end', () => {
    const out = movePluginsInText(sample, ['A.esp'], 99);
    expect(names(out).at(-1)).toBe('A.esp');
  });

  it('throws when any requested plugin is absent', () => {
    expect(() => movePluginsInText(sample, ['A.esp', 'No Such.esp'], 0)).toThrow(/No Such\.esp/);
  });

  it('preserves a leading BOM when the moved block includes the first line', () => {
    const out = movePluginsInText('\uFEFF*A.esp\r\nB.esp\r\nC.esp\r\n', ['A.esp'], 2);
    expect(out).toBe('\uFEFFB.esp\r\nC.esp\r\n*A.esp\r\n');
  });

  it('keeps comment/blank lines at their absolute position (only entries move)', () => {
    const text = '# top\r\n*A.esp\r\n\r\n# mid\r\nB.esp\r\nC.esp\r\n';
    const out = movePluginsInText(text, ['C.esp'], 0);
    expect(names(out)).toEqual(['C.esp', 'A.esp', 'B.esp']);
    // non-entry lines stay put: header still line 1, blank + "# mid" still bracket the middle
    expect(out.startsWith('# top\r\n')).toBe(true);
    expect(out).toContain('\r\n\r\n# mid\r\n');
  });
});
